### ISSUE TITLE
SSLSocketFactory with self-signed certificates

### ISSUE THREAD

**Issue by andreaanzalone** [joaocruz04/JSoap#5]
Hi!
I'm using your library in my app and now I have to establish a secure connection to a server that uses a self-signed certificate. In the soap-2 library documentation I read that with this little modification it's possible to add this feature:

<img width="933" alt="feature2" src="https://cloud.githubusercontent.com/assets/14835098/10097964/8f55ba70-637d-11e5-9138-9bf012ababac.png">

It would be possible to modify your library in this way?

**Comment by prakharprakhar89** [comment]
javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
12-30 15:18:57.012 9061-13451/? W/System.err:     at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:322)
12-30 15:18:57.012 9061-13451/? W/System.err:     at com.android.okhttp.Connection.upgradeToTls(Connection.java:201)
12-30 15:18:57.012 9061-13451/? W/System.err:     at com.android.okhttp.Connection.connect(Connection.java:155)
12-30 15:18:57.012 9061-13451/? W/System.err:     at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:276)
12-30 15:18:57.012 9061-13451/? W/System.err:     at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:211)
12-30 15:18:57.012 9061-13451/? W/System.err:     at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:382)
12-30 15:18:57.012 9061-13451/? W/System.err:     at com.android.okhttp.internal.http.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:106)
12-30 15:18:57.012 9061-13451/? W/System.err:     at com.android.okhttp.internal.http.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:217)
12-30 15:18:57.012 9061-13451/? W/System.err:     at com.android.okhttp.internal.http.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:218)
12-30 15:18:57.013 9061-13451/? W/System.err:     at com.android.okhttp.internal.http.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:25)
12-30 15:18:57.014 9061-13451/? W/System.err:     at org.ksoap2.transport.ServiceConnectionSE.openOutputStream(ServiceConnectionSE.java:126)
12-30 15:18:57.014 9061-13451/? W/System.err:     at org.ksoap2.transport.HttpTransportSE.call(HttpTransportSE.java:185)
12-30 15:18:57.014 9061-13451/? W/System.err:     at org.ksoap2.transport.HttpTransportSE.call(HttpTransportSE.java:118)
12-30 15:18:57.014 9061-13451/? W/System.err:     at org.ksoap2.transport.HttpTransportSE.call(HttpTransportSE.java:113)
12-30 15:18:57.014 9061-13451/? W/System.err:     at pt.joaocruz04.lib.SOAPManager$1.doInBackground(SOAPManager.java:67)
12-30 15:18:57.015 9061-13451/? W/System.err:     at pt.joaocruz04.lib.SOAPManager$1.doInBackground(SOAPManager.java:49)
12-30 15:18:57.015 9061-13451/? W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:292)
12-30 15:18:57.015 9061-13451/? W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
12-30 15:18:57.015 9061-13451/? W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
12-30 15:18:57.015 9061-13451/? W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
12-30 15:18:57.015 9061-13451/? W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
12-30 15:18:57.015 9061-13451/? W/System.err:     at java.lang.Thread.run(Thread.java:818)
12-30 15:18:57.016 9061-13451/? W/System.err: Caused by: java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
12-30 15:18:57.016 9061-13451/? W/System.err:     at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:324)
12-30 15:18:57.016 9061-13451/? W/System.err:     at com.android.org.conscrypt.TrustManagerImpl.checkServerTrusted(TrustManagerImpl.java:225)
12-30 15:18:57.016 9061-13451/? W/System.err:     at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:114)
12-30 15:18:57.016 9061-13451/? W/System.err:     at com.android.org.conscrypt.OpenSSLSocketImpl.verifyCertificateChain(OpenSSLSocketImpl.java:550)
12-30 15:18:57.016 9061-13451/? W/System.err:     at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
12-30 15:18:57.016 9061-13451/? W/System.err:     at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:318)
12-30 15:18:57.017 9061-13451/? W/System.err: 	... 21 more
12-30 15:18:57.017 9061-13451/? W/System.err: Caused by: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
12-30 15:18:57.017 9061-13451/? W/System.err: 	... 27 more
12-30 15:18:57.018 9061-13451/? V/hELLO: Network error
